Feature/get movie times list
f-lab-edu/Ticketing pull request #42
Opened 2022-06-27 19:13 UTC by changhyuns

## 작업 분류
- [x] 기능 추가
- [ ] 코드 수정
- [ ] 환경 설정

<br/>

## 구현 세부 내용
+ 영화 시간표 목록 조회 (영화 제목, 상영 날짜)
  + MovieTime Controller - GET 메서드 API 작성

<br/>

## 코드 변경 이유 (코드 수정이 아닌 경우 공란)

<br/>

## 리뷰 요청 사항

<br/>

## 질문

<br/>

## 체크 리스트
- [x] 프로젝트 빌드 및 실행이 정상적으로 동작하는지 확인했습니다.
- [x] 구현 사항에 대한 테스트를 완료했습니다.
- [x] 의도한 내용 이외에 다른 코드에는 변경 사항이 없는지 확인했습니다.
- [x] 코드 스타일을 적용하여 팀 코딩 컨벤션에 맞게 작성했습니다.

2022-06-28 09:57 UTC, kdhyo commented on server/src/main/java/com/ticketing/server/movie/application/MovieTimeController.java
> +        @ApiParam(value = "검색 단어", required = true) @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate runningDate) {
`runningDate` 의 @ApiParam value 가 `검색 단어`인데 혹시 의도하신 바가 있으신걸까요??

2022-06-28 12:02 UTC, changhyuns commented on server/src/main/java/com/ticketing/server/movie/application/MovieTimeController.java
> +        @ApiParam(value = "검색 단어", required = true) @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate runningDate) {
@kdhyo 앗..수정하겠습니다 ㅎㅎ

2022-06-28 12:47 UTC, f-lab-justin requested changes

2022-06-28 12:47 UTC, f-lab-justin commented on server/src/test/java/com/ticketing/server/movie/service/MovieTImeServiceImplTest.java
> +public class MovieTImeServiceImplTest {
@changhyuns 
오타요~ ㅎㅎ

2022-06-28 12:47 UTC, f-lab-justin commented on server/src/main/java/com/ticketing/server/movie/service/dto/MovieTimeDto.java
> +    private LocalTime startAt;
@changhyuns 
같이 CGV예제를 살펴봤는데요! LocalDateTime을 고민해보시지요!

2022-06-28 12:47 UTC, f-lab-justin commented on server/src/main/java/com/ticketing/server/movie/service/MovieTimeServiceImpl.java
> +    private static RuntimeException throwMovieNotFound() {
@changhyuns 
예외를 어떻게 구성하면 좋을지 고민해보세요! (별도의 파일 등)

2022-06-30 18:25 UTC, changhyuns commented on server/src/main/java/com/ticketing/server/movie/service/MovieTimeServiceImpl.java
> +    }
@kdhyo @f-lab-justin 
심야 영화는 무조건 다음날 06시 이전에 시작하고
조조 영화는 무조건 다음날 06시 이후에 시작한다고 판단하여
날짜 기준으로 영화를 검색할 때 당일 00시 ~ 익일 06시 까지의 영화 시간표를 리턴하도록 수정했습니다.
확인 부탁드립니다.

2022-06-30 18:28 UTC, changhyuns commented on server/src/main/java/com/ticketing/server/movie/service/dto/MovieTimeDto.java
> +    private LocalTime startAt;
수정했습니다.

2022-06-30 18:28 UTC, changhyuns commented on server/src/test/java/com/ticketing/server/movie/service/MovieTImeServiceImplTest.java
> +public class MovieTImeServiceImplTest {
수정했습니다.

2022-06-30 19:11 UTC, changhyuns commented on server/src/main/java/com/ticketing/server/movie/application/MovieTimeController.java
> +        @ApiParam(value = "검색 단어", required = true) @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate runningDate) {
수정했습니다.

2022-07-01 04:35 UTC, kdhyo commented on server/src/main/java/com/ticketing/server/movie/domain/MovieTime.java
> +//	}
주석은 이전 커밋기록에 남아있으니 지워도 될 것 같아요!

2022-07-01 18:14 UTC, changhyuns commented on server/src/main/java/com/ticketing/server/movie/domain/MovieTime.java
> +//	}
수정했습니다 :)

2022-07-03 15:36 UTC, merged