#1 기본설정
f-lab-edu/Ticketing pull request #9
Opened 2022-04-27 14:49 UTC by kdhyo

## 작업 내용
- [ ] 사용할 디펜던시 추가
- [ ] Groovy Grade -> Kotlin Gradle DSL
- [ ] .gitignore 작성
- [ ] DB 설정 정보 작성
- [ ] yml 환경 별 분리
- [ ] 코드컨벤션 파일 추가

<br/>

## 구현 세부 내용

<br/>

## 코드 변경 이유 (코드 수정이 아닌 경우 공란)

<br/>

## 리뷰 요청 사항

<br/>

## 질문

<br/>

## 체크 리스트
- [ ] 프로젝트 빌드 및 실행이 정상적으로 동작하는지 확인했습니다.
- [ ] SpringBoot 환경 테스트 동작을 확인했습니다.

2022-04-27 15:06 UTC, kdhyo commented on server/build.gradle.kts
> +}
이 부분이 잘 이해가 가지 않습니다.. ㅜㅜ

현재 이해한 것으로는 `annotationProcessor ("org.projectlombok:lombok")` 을 가지고와서
`compilOnly` 에 등록해주는 걸로 이해했는데 .. 맞다면,
`compileOnly ("org.projectlombok:lombok")` 이 부분은 없어도 되는걸까요??

2022-04-27 15:07 UTC, kdhyo commented on server/src/main/resources/application-local.yml
> +    url: jdbc:mysql://localhost:3306/ticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
국내 서비스로 생각을 하고,
`UTC`가 아닌 `serverTimezone=Asia/Seoul` 우리나라 시간으로 설정을 했는데 괜찮을까요??

2022-04-27 15:10 UTC, kdhyo commented on server/src/test/java/com/ticketing/server/ServerApplicationTests.java
> +	}
멘토링 시간때 일단 테스트 코드가 돌아가는 지 확인하는 부분이 있으면 좋겠다고 말씀 하셨었는데,
어떤 걸 넣어서 확인해야할지 감이 안잡혀 일단 `@SpringBootTest` 가 동작하는지만 확인했습니다.

추가로 넣어야 할 부분이 있을까요??

2022-04-30 15:47 UTC, f-lab-justin commented on server/build.gradle.kts
> +}
@kdhyo 
저도 이게 궁금해서 좀 찾아봤는데..소스상으로는 중복이 맞는 것 같습니다만(compileOnly에서 빼던가, configurations를 지우던가가 해도 컴파일은 잘 되네요!)..intellij에서 해당 설정을 기준으로 annotationProcessor를 자동으로 구성한다고 합니다. 사실 저는 예전부터 쓰다보니 그냥 습관적으로 annotation processor를 항상 켜두던지라 잘 몰랐었는데 이번에 알게 되었네요~! 참고 부탁드립니다!

https://kdevkr.github.io/lombok-annotation-processor/

2022-04-30 15:48 UTC, f-lab-justin commented on server/src/main/resources/application-local.yml
> +    url: jdbc:mysql://localhost:3306/ticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
@kdhyo 
문제 없을것 같습니다!

2022-04-30 15:50 UTC, f-lab-justin commented on server/src/test/java/com/ticketing/server/ServerApplicationTests.java
> +	}
@kdhyo 
음..보통의 경우 사용할 DB등의 설정이 잘 동작하는지, 기본 설정들이 test phase에서도 잘 먹는지 등을 확인하게 되는데요. 현재 올려주신 PR은 아직 관련 코드가 없어서 별다르게는 없을 것 같습니다~!

2022-04-30 15:56 UTC, f-lab-justin requested changes
나중에 수정해도 되지만 DB 설정 관련한 필드들을 좀 더 살펴보고 connection 관련 값들도 한번 공부해서 설정해놓으시면 좋을 것 같습니다.

2022-04-30 16:08 UTC, changhyuns commented on server/src/test/java/com/ticketing/server/ServerApplicationTests.java
> +	}
@f-lab-justin 

아직 클라우드 서버가 없어서 공용으로 사용할 DB가 없는데
초기 개발 단계에서 DB는 각자 로컬 연결해서 사용하면 될까요 ?

2022-04-30 16:17 UTC, changhyuns commented
**LGTM**
DB 로컬로 사용할 경우
계정명이랑 비밀번호 맞추고 properties 추가하면 될 것 같습니다!

2022-04-30 16:30 UTC, f-lab-justin commented on server/src/test/java/com/ticketing/server/ServerApplicationTests.java
> +	}
@changhyuns @kdhyo 
음 초기 개발 단계에서는 H2 기반의 테스트 위주로 진행되어도 됩니다. 그래도 개발서버가 있는게 좀 더 용이할 것 같은데요. 제가 알기로 f-lab에서 네이버클라우드 크레딧을 제공하는 걸로 알고 있어요.(멘티 가이드에 있다고 들었습니다!) 어느 정도 기본적인 설정들이 완료되어서 본격적으로 로직 개발에 들어가는 시점이 되기 전에 두분이 협의하셔서 적절한 시점에 개발서버를 생성하시면 좋을 것 같습니다.

2022-04-30 16:37 UTC, changhyuns commented on server/src/test/java/com/ticketing/server/ServerApplicationTests.java
> +	}
@f-lab-justin 
네 알겠습니다!
초기 패키지 및 엔티티 생성하고 동작 확인하고 나면
네이버 클라우드 이용해서 개발 서버 DB 사용해보겠습니다 :)

2022-05-01 12:26 UTC, kdhyo commented on server/build.gradle.kts
> +}
감사합니다!!
사이트 글을 몇 번 읽어보니까 이해가 됐어요!!! :)

2022-05-02 09:12 UTC, kdhyo commented on server/src/main/resources/application.yml
> +      max-lifetime: 1800000 # default 30 minutes
현재는 아직 local로만 작업 진행 중이기에 기준 없이 default 옵션에서 변경한다는 생각이 들어,
hikariCP 옵션 중 나중에 서버셋팅 및 성능테스트 후 튜닝 할 수 있을 것 같은 옵션들을 적어보았습니다!

혹시 이 외에도 튜닝할 옵션 혹은 저 중에서도 실무에서 변경하지 않는 옵션이 있는지 궁금합니다!

2022-05-02 10:44 UTC, kdhyo commented on server/src/main/resources/application.yml
> +        maintainTimeStats: false
MySQL 설정 정보 중 hikari 에서 권장하는 정보를 일단 적용해보았습니다.

----데이터 캐싱----
cachePrepStmts : PreparedStatement Caching 을 활성화 합니다.
prepStmtCacheSize : Connection 별 캐싱할 PreparedStatement 개수
prepStmtCacheSqlLimit : MySQL 드라이버가 캐싱할 PreparedStatement 의 최대 길이
useServerPrepStmts : Server-Side PreparedStatement 를 사용한다. (기본은 Client-Side 를 사용한다. 이 부분은 실제 테스트 시 더 느리다는 얘기가 있기에 나중에 테스트 진행해보아야 할듯.)

----잦은 작업 줄이기----
useLocalSessionState : 불필요한 autocommit 을 남기지 않도록 하는 옵션
cacheResultSetMetadata : 쿼리문들을 실행한 후 결과 값들을 캐싱하는 옵션
cacheServerConfiguration : 드라이버 URL 별로 show variables, show collation 결과를 캐시하는 옵션
elideSetAutoCommits : setAutoCommit() 으로 설정된 값과 MySQL 서버의 autocommit 값이 다를 때만 SET autocommit 명령을 전송하게 하는 옵션
maintainTimeStats : 연결 실패 시 더 자세한 메시지를 위해 내부 타이머가 유지되어야 할 경우 true, false 일 시 퀴리 당 System.getCurrentTimeMillis()에 대한 두 번 이상의 호출이 제거됩니다.

----기타옵션----
rewriteBatchedStatements : insert batch 성능을 향상시키는 옵션 / insert query를 합칠 수 있게 해주는 옵션




----공식문서----
https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-performance-extensions.html

----참고 블로그----
https://2ssue.github.io/programming/HikariCP-MySQL/
https://kwonnam.pe.kr/wiki/database/mysql/jdbc
https://vladmihalcea.com/mysql-jdbc-statement-caching/

2022-05-02 10:48 UTC, kdhyo commented on server/src/main/resources/application.yml
> +        maintainTimeStats: false
궁금한 점
- 실제로 위 옵션들을 다 설정 고려 하는지 궁금합니다!!

- 다른 옵션들은 어느정도 이해가 가는데  
`useLocalSessionState` 이 옵션은 정확히 어떤 commit을 남지 않게 하는지 이해가 가질 않습니다..

2022-05-02 10:53 UTC, kdhyo commented on server/src/main/resources/application-local.yml
> +    url: jdbc:mysql://localhost:3306/ticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
@f-lab-justin 
hikari 설정을 하다보니 `datasurce.hikari.jdbc-url` 로 설정하는 방법도 있었습니다.
하지만, 위 경로로 url을 설정할 경우 java 코드로 config 설정을 수동으로 해주어야만 실행이 됐습니다.

개인적으로는 yml로 모아서 보는 게 javacode 로 config 설정하는 것 보다 좋다고 생각이 드는데,
멘토님은 어떤 방식을 선호하는지 또는 어떤 상황에서 javaCode로 config 파일을 별도로 만드는지 궁금합니다!

```
@ConfigurationProperties("spring.datasource.hikari")
public DataSource dataSource() {
	return DataSourceBuilder.create()
		.type(HikariDataSource.class)
		.build();
}
```

2022-05-02 13:55 UTC, f-lab-justin commented on server/src/test/java/com/ticketing/server/ServerApplicationTests.java
> +	}
@changhyuns 
1. 혹시 서버 내에 mysql 을 설치하는 것과 mysql 도커 이미지를 사용하는 것에는
차이는 없는건가요 ?
=> 차이가 있죠..docker를 잘 설정해서 사용하셔야 합니다. docker의 경우 그냥 설치하는 것보다 약간의 performance 저하는 있겠지만, 그 저하를 상쇄하는 많은 이득도 있어서d요. docker에 대한 경험을 해보시고 싶다면 하셔도 큰 무리 없습니다.

2. 실서비스용이라면 노출하지 않아야 하죠..저희 회사에서는 vault를 사용해서 관련 정보들을 저장하고 로딩하고 있습니다만, 일단 현재는 jasypt정도로 괜찮지 않을까 싶어요. 아니면 앱 실행시 인자로 넘겨도 될 것 같습니다.

2022-05-02 14:02 UTC, f-lab-justin commented on server/src/main/resources/application.yml
> +      max-lifetime: 1800000 # default 30 minutes
@kdhyo 
넵~ 저 옵션들을 잘 설정하면 왠만한 것들은 다 다룰 수 있습니다.

2022-05-02 14:05 UTC, f-lab-justin commented on server/src/main/resources/application.yml
> +        maintainTimeStats: false
@kdhyo 
위의 옵션들은 저도 사용해보지 않았는데요;; 현재로서는 없어도 될 것 같습니다. 
https://github.com/brettwooldridge/HikariCP 
여기의 옵션들을 참고하시는게 좋을 것 같습니다.

2022-05-02 14:06 UTC, f-lab-justin commented
@kdhyo @changhyuns 
고생하셨습니다~!

2022-05-02 14:07 UTC, f-lab-justin approved these changes
@kdhyo @changhyuns 
고생하셨습니다. 일단 고고 하시지요

2022-05-02 14:22 UTC, merged

2022-05-02 14:30 UTC, kdhyo commented on server/src/main/resources/application.yml
> +        maintainTimeStats: false
@f-lab-justin 
아하..!
hikaricp WIKI 에서 [MySQL Configuration Tips](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration)
이렇게 있길래 사용하는줄알고 찾아봤었는데 실무에서는 사용하는 건 아니었나보네요 .. ㅜㅜ